const { test, expect } = require('@playwright/test');
require('dotenv').config();

let api;
let userId;
let postId;

const BASE_URL = process.env.GOREST_BASE_URL || 'https://gorest.co.in/public/v2';
const token = process.env.GOREST_TOKEN;

if (!token) {
  console.warn('⚠️ GOREST_TOKEN is missing. API tests will be skipped.');
}

// Generate a unique email each run
function uniqueEmail() {
  return `pw_user_${Date.now()}_${Math.floor(Math.random() * 1000)}@example.com`;
}

test.describe('GoREST API - Users & Posts', () => {
  // ========================
  // BEFORE ALL
  // ========================
  test.beforeAll(async ({ playwright }) => {
    api = await playwright.request.newContext({
      baseURL: BASE_URL,
      extraHTTPHeaders: {
        Accept: 'application/json',
        ...(token ? { Authorization: `Bearer ${token}` } : {})
      }
    });
  });

  // ========================
  // AFTER ALL
  // ========================
  test.afterAll(async () => {
    await api.dispose();
  });

  // ========================
  // GET USERS
  // ========================
  test('GET /users', async () => {
    test.skip(!token, 'Token is required to fetch users');

    const res = await api.get('/users', { params: { page: 1, per_page: 5 } });

    if (res.status() !== 200) {
      console.error('GET /users failed, response:', await res.text());
    }

    expect(res.status()).toBe(200);

    const body = await res.json();
    expect(Array.isArray(body)).toBe(true);
  });

  // ========================
  // FULL CRUD LIFECYCLE
  // ========================
  test('Full CRUD lifecycle on /users', async () => {
    test.skip(!token, 'Token is required for create/update/delete');

    // CREATE USER
    const email = uniqueEmail();
    const createRes = await api.post('/users', {
      json: {
        name: 'Playwright User',
        email,
        gender: 'male',
        status: 'active'
      }
    });

    if (!createRes.ok()) {
      console.error('CREATE /users failed, response:', await createRes.text());
    }
    expect(createRes.status()).toBe(201);

    const newUser = await createRes.json();
    userId = newUser.id;

    // GET USER
    const getRes = await api.get(`/users/${userId}`);
    expect(getRes.status()).toBe(200);

    // UPDATE USER
    const patchRes = await api.patch(`/users/${userId}`, {
      json: { name: 'Updated Name' }
    });
    expect(patchRes.status()).toBe(200);

    const updatedUser = await patchRes.json();
    expect(updatedUser.name).toBe('Updated Name');

    // CREATE POST
    const postRes = await api.post('/posts', {
      json: {
        user_id: userId,
        title: 'Test Post',
        body: 'Generated by Playwright'
      }
    });
    expect(postRes.status()).toBe(201);

    const postObj = await postRes.json();
    postId = postObj.id;

    // DELETE POST
    const delPost = await api.delete(`/posts/${postId}`);
    expect([200, 204]).toContain(delPost.status());

    // DELETE USER
    const delUser = await api.delete(`/users/${userId}`);
    expect([200, 204]).toContain(delUser.status());
  });
});
