const { test, expect } = require('@playwright/test');
require('dotenv').config();

const token = process.env.GOREST_TOKEN;
const baseURL = process.env.GOREST_BASE_URL || 'https://gorest.co.in/public/v2';

function uniqueEmail() {
  const id = Date.now();
  return `testuser_${id}@example.com`;
}

test.describe('GoREST API CRUD Tests', () => {
  let api;
  let userId;
  let postId;

  test.beforeAll(async ({ playwright }) => {
    api = await playwright.request.newContext({
      baseURL,
      extraHTTPHeaders: token
        ? { Authorization: `Bearer ${token}` }
        : {}
    });
  });

  test.afterAll(async () => {
    await api.dispose();
  });

  test('GET /users', async () => {
    const res = await api.get('/users?page=1&per_page=5');
    expect(res.status()).toBe(200);

    const body = await res.json();
    expect(Array.isArray(body)).toBe(true);
  });

  test('Full CRUD lifecycle on /users', async () => {
    test.skip(!token, 'Token is required for create/update/delete');

    // CREATE USER
    const email = uniqueEmail();
    const createRes = await api.post('/users', {
      data: {
        name: 'Playwright User',
        email,
        gender: 'male',
        status: 'active'
      }
    });

    expect(createRes.ok()).toBe(true);
    const newUser = await createRes.json();
    userId = newUser.id;

    // GET USER
    const getRes = await api.get(`/users/${userId}`);
    expect(getRes.status()).toBe(200);

    // UPDATE USER
    const patchRes = await api.patch(`/users/${userId}`, {
      data: { name: 'Updated Name' }
    });
    const updatedUser = await patchRes.json();
    expect(updatedUser.name).toBe('Updated Name');

    // CREATE POST FOR USER
    const postRes = await api.post('/posts', {
      data: {
        user_id: userId,
        title: 'Test Post',
        body: 'Generated by Playwright'
      }
    });

    expect(postRes.status()).toBe(201);
    const postObj = await postRes.json();
    postId = postObj.id;

    // DELETE POST
    const delPost = await api.delete(`/posts/${postId}`);
    expect([200, 204]).toContain(delPost.status());

    // DELETE USER
    const delUser = await api.delete(`/users/${userId}`);
    expect([200, 204]).toContain(delUser.status());
  });
});
